name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-and-lint:
    name: Run tests and lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install golang
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15.0'
      - run: go test ./...
      - run: '! go fmt ./... 2>&1 | read'
